// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG92laIVT66N3i0rDQ6R3MLwOVw1eDRBM',
    appId: '1:911578190458:web:0c2ffd6e0d3bb1f63aa1c3',
    messagingSenderId: '911578190458',
    projectId: 'instax-df298',
    authDomain: 'instax-df298.firebaseapp.com',
    storageBucket: 'instax-df298.appspot.com',
    measurementId: 'G-1HQEEW7JLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAidEESjdcQ94Ah5gQ1F_snsmzVZ0l-7lM',
    appId: '1:911578190458:android:8d1611845562968e3aa1c3',
    messagingSenderId: '911578190458',
    projectId: 'instax-df298',
    storageBucket: 'instax-df298.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFvW7OZAtpWu3T2lAjSyQc88E-hsLTTRE',
    appId: '1:911578190458:ios:ddd23b1866f8d9c63aa1c3',
    messagingSenderId: '911578190458',
    projectId: 'instax-df298',
    storageBucket: 'instax-df298.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFvW7OZAtpWu3T2lAjSyQc88E-hsLTTRE',
    appId: '1:911578190458:ios:154866fac46f23033aa1c3',
    messagingSenderId: '911578190458',
    projectId: 'instax-df298',
    storageBucket: 'instax-df298.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
